### PR TITLE
Upgrade to VimClojure 2.3.6

### PR DESCRIPTION
**Pull request by ctford**
Upgraded past the broken versions 2.3.4 and 2.3.5 through to 2.3.6. See issue #12.

### CODE REVIEW

**Comment by daveray** [comment]
You're a gentleman and a scholar :)
Does this include the `fix-window-handling.diff` patch that Meikel posted to the ML yesterday? I didn't get the impression he had cut a new release yet.

**Comment by ctford** [comment]
Ah no, it doesn't. I guess that will be 2.3.6 when it's done. Maybe we should wait for that.

I've been getting the releases from vim.org (http://www.vim.org/scripts/script.php?script_id=2501), which does have 2.3.5 now.

**Comment by daveray** [comment]
Yeah. I was going to wait for everything to shake out of that thread and for 2.3.6 before upgrading.

**Comment by ctford** [comment]
Makes sense. I'd missed the discussion on the second issue.

**Comment by ctford** [comment]
I've updated the pull request through to 2.3.6, and it works locally for me.

**Comment by daveray** [comment]
Works for me too. Thanks a lot for tracking this!

**Pull request merged**
